var box = Document.getElementById("box");
var screen = box.children[0];
var ul = screen.children[0];
var ol = screen.children[1];
var lisul= ul.children;
var imgwid = screen.offsetWidth;
var arr = box.children[1];
var arrleft =arr.children[0];
var arrleft = arr.children[1];
for(var i=0;i<lisul.length)
